# data
root_data_path: 'DATASET/MalNet/full-data/malnet-images/'
train_set_json: 'data_info/without_type_whole/steps_family_samples_train.json'
test_set_json: 'data_info/without_type_whole/steps_family_samples_test.json'
hash_type_dict: 'statistics_without_type_whole_all_families/hash_type_dict.pkl'
batch_size: 128
mode: 'new'  # 'new' or 'both'
# exemplar_numper_per_class_per_step: 3
exemplar_budget: 10000
exemplar_strategy: 'random'
img_norml: False

# model
res18_weights: 'imagenet'  # 'random' or 'imagenet'
lamda: 1  #  [0.1, 5]
LSC: False
adaptation: True

# training
learning_rate: 1e-4
weight_decay: 1e-4
num_epochs: 100

# misc
gpu_id: 1
il_trainer: 'icarl'
random_seed: 42
exp_tag: 'icarl_full_exemplar'