# data
root_data_path: 'DATASET/MalScan_MalNet'
train_set_json: '../data_info/without_type_whole/steps_family_samples_train.json'
test_set_json: '../data_info/without_type_whole/steps_family_samples_test.json'
hash_type_dict: '../statistics_v3_without_type_whole_all_families/hash_type_dict.pkl'
batch_size: 128
mode: 'both'  # 'new' or 'both'
# exemplar_numper_per_class_per_step: 0
exemplar_budget: 0
img_norml: False

# model
res18_weights: 'imagenet'  # 'random' or 'imagenet'
LSC: False

# training
learning_rate: 1e-4
weight_decay: 1e-4
num_epochs: 100

# misc
gpu_id: 0
il_trainer: 'fine_tune'
random_seed: 42
exp_tag: 'upper_bound_full'
shift_eval: False